<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="OperationResultTools" Version="1.0.29" />
    <PackageReference Include="TinyHelpers" Version="3.2.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatApplication.DataAccessLayer\ChatApplication.DataAccessLayer.csproj" />
    <ProjectReference Include="..\ChatApplication.Shared\ChatApplication.Shared.csproj" />
    <ProjectReference Include="..\ChatApplication.StorageProviders\ChatApplication.StorageProviders.csproj" />
  </ItemGroup>

</Project>
