<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TinyHelpers" Version="3.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatApplication.DataAccessLayer\ChatApplication.DataAccessLayer.csproj" />
    <ProjectReference Include="..\ChatApplication.Shared\ChatApplication.Shared.csproj" />
    <ProjectReference Include="..\ChatApplication.StorageProviders\ChatApplication.StorageProviders.csproj" />
  </ItemGroup>

</Project>
